[package]
name = "fast-socket-examples"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
fast-socket-benchmarks = { path = "../benchmarks" }
fast-socket-async-rs = { path = "../crates/fast-socket-async-rs" }
fast-socket-os-rs = { path = "../crates/fast-socket-os-rs" }
fast-socket-rs = { path = "../crates/fast-socket-rs" }
fast-socket-xdp-rs = { path = "../crates/fast-socket-xdp-rs" }
libc = "0.2"
tokio = { version = "1", features = ["macros", "rt", "time"] }

[[bin]]
name = "udp-echo"
path = "src/bin/udp-echo.rs"

[[bin]]
name = "udp-pong"
path = "src/bin/udp-pong.rs"

[[bin]]
name = "udp-discard"
path = "src/bin/udp-discard.rs"

[[bin]]
name = "udp-proxy"
path = "src/bin/udp-proxy.rs"

[[bin]]
name = "udp-tokio-echo"
path = "src/bin/udp-tokio-echo.rs"

[[bin]]
name = "udp-tokio-pong"
path = "src/bin/udp-tokio-pong.rs"

[[bin]]
name = "udp-tokio-discard"
path = "src/bin/udp-tokio-discard.rs"

[[bin]]
name = "udp-tokio-proxy"
path = "src/bin/udp-tokio-proxy.rs"

[[bin]]
name = "udp-xdp-static-route-blast"
path = "src/bin/udp-xdp-static-route-blast.rs"
