[package]
name = "fast-socket-benchmarks"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
fast-socket-rs = { path = "../crates/fast-socket-rs" }
fast-socket-os-rs = { path = "../crates/fast-socket-os-rs" }
fast-socket-xdp-rs = { path = "../crates/fast-socket-xdp-rs" }
libc = "0.2"
